version: "3"
services:
  build:
    image: gradle
    volumes:
      - .:/src
    network_mode: bridge
    working_dir: /src
    command: gradle bootJar
  app:
    build: .
    ports:
      - "8080:8080"